name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    name: Python ${{ matrix.python-version }}
    steps:

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -e .

    - name: Test with pytest
      run: |
        pytest

    - name: Check coverage
      run: |
        pytest --cov=cli --cov=pythonanywhere --cov=scripts --cov-fail-under=65
